### ISSUE TITLE
winterpy/pylib/QQWry.py

### ISSUE THREAD

**Issue by micfan** [lilydjwg/winterpy#9]
解析小库，怎么写的这么复杂

**Comment by lilydjwg** [comment]
我不是原作者，也不知道啦。求 patch～

**Comment by micfan** [comment]
这个轮子不错，我试了最新数据库解析成功https://github.com/gwind/ylinux/blob/master/tools/IP/QQWry/qqwry.py

**Comment by lilydjwg** [comment]
你给的那个链接是 Python 2 版本的。注释详尽，但是代码有些不尽如人意，如 `decode_str` 本应使用 `errors="replace"`，`mmap.mmap(self.db.fileno(), 0, access = 1)` 有多少人知道这里的 `access = 1` 是个啥？

**Comment by micfan** [comment]
查查文档不就知道了？

**Comment by lilydjwg** [comment]
你的意思是 C 的各种常量宏、枚举类型、Python 3.4 新加入的 enum 都是一群不想查文档的人偷懒的结果？
